update: Changelog and neovim plugins add

diff --git a/zsh/themes/charMulti b/zsh/themes/charMulti
--- a/zsh/themes/charMulti
+++ b/zsh/themes/charMulti
@@ -24,9 +24,55 @@ function status_word {
   fi
 }
 
-# Variable to track arrow direction
-ARROW_DIRECTION="»"
+# --- theme:duration ---
+# Variables for tracking command duration
+typeset -g _prompt_cmd_timestamp
+typeset -g _prompt_cmd_duration
 
+# Function to format duration nicely
+function format_duration {
+  local duration=$1
+  local hours=$((duration / 3600))
+  local minutes=$(((duration % 3600) / 60))
+  local seconds=$((duration % 60))
+  
+  if [[ $duration -lt 1 ]]; then
+    echo ""
+  elif [[ $hours -gt 0 ]]; then
+    printf "%dh %dm %ds" $hours $minutes $seconds
+  elif [[ $minutes -gt 0 ]]; then
+    printf "%dm %ds" $minutes $seconds
+  else
+    printf "%ds" $seconds
+  fi
+}
+
+# Function to display duration (Rosé Pine colors)
+function duration_info {
+  if [[ -n $_prompt_cmd_duration ]]; then
+    local formatted=$(format_duration $_prompt_cmd_duration)
+    if [[ -n $formatted ]]; then
+      echo -n "%F{#9ccfd8}${formatted}%f"
+    fi
+  fi
+}
+
+# Record timestamp before command execution
+function record_start_time {
+  _prompt_cmd_timestamp=$EPOCHSECONDS
+}
+
+# Calculate duration after command execution
+function record_end_time {
+  local exit_code=$?
+  if [[ -n $_prompt_cmd_timestamp ]]; then
+    _prompt_cmd_duration=$((EPOCHSECONDS - _prompt_cmd_timestamp))
+    unset _prompt_cmd_timestamp
+  fi
+  return $exit_code
+}
+
+# --- theme:vcs ---
 # Initialize vcs_info for git branch display
 autoload -Uz vcs_info
 setopt prompt_subst
@@ -39,66 +85,22 @@ zstyle ':vcs_info:*' actionformats '%F{5}%F{#c4a7e7}%b%F{#f6c177}|%F{#eb6f92}%a%
 zstyle ':vcs_info:*' formats '%F{5}%F{#c4a7e7}%b%c%u%F{5}%f '  # iris purple branch name
 zstyle ':vcs_info:svn:*' branchformat '%b'
 zstyle ':vcs_info:svn:*' actionformats '%F{5}%F{#c4a7e7}%b%F{#eb6f92}:%F{#f6c177}%i%F{#f6c177}|%F{#eb6f92}%a%c%u%F{5}%f '
-zstyle ':vcs_info:svn:*' formats '%F{#c4a7e7}%b%F{#eb6f92}:%F{#f6c177}%i%c%u%F{5}%f '
+zstyle ':vcs_info:svn:*' formats '%F{5}%F{#c4a7e7}%b%F{#eb6f92}:%F{#f6c177}%i%c%u%F{5}%f '
 zstyle ':vcs_info:*' enable git cvs svn
 
-# Custom backspace widget
-function my-backward-delete-char() {
-  ARROW_DIRECTION="«"
-  zle backward-delete-char
-  zle reset-prompt
-}
-
-# Custom self-insert widget to catch normal typing
-function my-self-insert() {
-  ARROW_DIRECTION="»"
-  zle self-insert
-  zle reset-prompt
-}
-
-# Custom accept-line to reset arrow
-function my-accept-line() {
-  ARROW_DIRECTION="»"
-  zle accept-line
-}
-
-# Create the widgets
-zle -N my-backward-delete-char
-zle -N my-self-insert
-zle -N my-accept-line
-
-# Bind the widgets
-bindkey '^?' my-backward-delete-char  # Backspace
-bindkey '^H' my-backward-delete-char  # Ctrl+H
-bindkey '^M' my-accept-line  # Enter
-
-# Override the default self-insert to catch normal typing
-for key in {a..z} {A..Z} {0..9}; do
-  bindkey "$key" my-self-insert
-done
-
-# Common symbols
-bindkey ' ' my-self-insert
-bindkey '.' my-self-insert
-bindkey ',' my-self-insert
-bindkey '!' my-self-insert
-bindkey '?' my-self-insert
-bindkey ':' my-self-insert
-bindkey ';' my-self-insert
-
+# --- theme:precmd ---
 # Function to update vcs_info and reset arrow after command
 theme_precmd() {
   vcs_info
-  # Reset arrow to default after command execution
-  ARROW_DIRECTION="»"
-  # Print the time/date on the line above
-  # print -rP '%W %B%F{#c4a7e7}%t%f%b'
+  record_end_time
 }
 
-# Set up the prompt with dynamic vcs_info (Rosé Pine colors)
-PROMPT=' $(cancer) (%(?,%F{#c4a7e7}success%f %?,%F{#eb6f92}failed%f %?) | %h) %{$reset_color%}${vcs_info_msg_0_}%{$reset_color%}
- [%F{#907aa9}%n%f: %~] ${ARROW_DIRECTION} '
+# --- theme:prompt ---
+# Set up the prompt with dynamic vcs_info and duration (Rosé Pine colors)
+PROMPT=' $(cancer) (%(?,%F{#c4a7e7}success%f %?,%F{#eb6f92}failed%f %?) | %h$(duration_info)) %{$reset_color%}${vcs_info_msg_0_}%{$reset_color%}
+ [%F{#907aa9}%n%f: %~] » '
 RPROMPT='%W %B%F{#c4a7e7}%t%f%b'
+
 
 # Add the precmd hook to update git info automatically
 autoload -U add-zsh-hook
